---
new_page_extension: md
auto_deploy: false
admin_path: "/"
webhook_url: 
sections:
- type: document
  path: docs/README.md
  label: Home
- type: directory
  path: docs/lists
  label: Lists
  create: all
  match: "**/*"
  templates:
  - default
- type: heading
  label: Journaux
- type: document
  path: docs/journal.md
  label: Journal
- type: document
  path: docs/yume.md
  label: Yume
- type: document
  path: docs/buy.md
  label: Buy list
- type: heading
  label: Trackers
- type: document
  path: docs/projects.md
  label: Projects
- type: heading
  label: Doc
- type: document
  path: docs/notebook.md
  label: Notebook
- type: document
  path: docs/yume-doc.md
  label: Yume Doc
- type: directory
  path: docs
  label: Docs
  create: all
  match: "**/*"
  templates:
  - default
- type: heading
  label: Portfolio
- type: document
  path: docs/portfolio/cv.md
  label: CV
- type: document
  path: docs/portfolio/README.md
  label: About
- type: directory
  path: docs/portfolio/cg
  label: Computer Graphics
  create: documents
  match: "**/*"
  templates:
  - default
upload_dir: docs/.vuepress/public/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: docs/.vuepress/dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
