---
new_page_extension: md
auto_deploy: false
admin_path: "/"
webhook_url: 
sections:
- type: directory
  path: docs/references
  label: References
  create: all
  match: "**/*.md"
  templates:
  - default
- type: document
  path: docs/README.md
  label: Home
- type: directory
  path: docs/.vuepress
  label: Config
  create: none
  match: "**/*"
- type: directory
  path: docs
  label: Docs
  create: all
  match: "**/*"
  templates:
  - default
- type: heading
  label: Journaux
- type: document
  path: docs/journal.md
  label: Journal
- type: document
  path: docs/yume.md
  label: Yume
- type: document
  path: docs/buy.md
  label: Buy list
- type: heading
  label: Trackers
- type: document
  path: docs/projects.md
  label: Projects
- type: heading
  label: Doc
- type: document
  path: docs/notebook.md
  label: Notebook
- type: document
  path: docs/yume-doc.md
  label: Yume Doc
upload_dir: assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: docs/.vuepress/dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
