---
label: default
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: title
  description: page title. Displayed in search engines and in browser tabs.
- name: lang
  type: text
  config:
    required: false
  label: lang
  description: Language of current page (en-US, fr)
- type: text
  name: description
  label: description
  description: page description, displayed under the title in search engines.
- name: sidebarDepth
  type: number
  label: sidebarDepth
  description: Setting it to <code>0</code> disables the header links, and the max
    value is <code>2</code> which extracts both <code>h2</code> and <code>h3</code>
    headers.
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: meta
  type: field_group_list
  fields:
  - name: name
    type: text
    config:
      required: false
    label: name
    description: meta tags name attribute. It can be "title", "description", "robots",
      etc...
  - name: content
    type: text
    config:
      required: false
    description: meta tags content attribute.
    label: content
  config:
    min: 
    max: 
    labelField: 
  label: meta
  description: Meta tags (useful for SEO).
pages:
- docs/buy.md
- docs/buy.md
- docs/combat-game.md
- docs/crème-légère.md
- docs/podcast.md
- docs/portfolio/README.md
- docs/portfolio/cg/poster-design.md
- docs/portfolio/cv.md
- docs/yume-doc.md
