---
label: default
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: title
  description: page title. Displayed in search engines and in browser tabs.
- name: lang
  type: text
  config:
    required: false
  label: lang
  description: Language of current page (en-US, fr)
- type: text
  name: description
  label: description
  description: page description, displayed under the title in search engines.
- name: meta
  type: field_group
  config: {}
  fields:
  # META TITLE
  - name: name
    type: text
    config:
      required: false
    label: name
    hidden: true
    default: title
  - name: content
    type: text
    config:
      required: false
    label: title
    description: meta title (useful for SEO).
  # META DESCRIPTION
  - name: name
    type: text
    config:
      required: false
    label: name
    hidden: true
    default: description
  - name: content
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: false
      schema:
        format: markdown
    label: description
    description: meta description (useful for SEO).
  # META ROBOTS
  - name: name
    type: text
    config:
      required: false
    label: name
    hidden: true
    default: robots
  - name: content
    type: tag_list
    default: []
    label: robots
    description: meta robots (useful for SEO) (follow, nofollow, index, noindex, none).
pages:
- docs/yume-doc.md
- docs/yume.md
